### ISSUE TITLE
Can not set test video

### ISSUE THREAD

**Issue by shootingliu** [kasakun/Fall-Detection#1]
Thanks for your great job.

But when I  test 'falling detection ver2.5',I found that I can not add the video in ,and always shows'directory not found'.  I use .mp4 or .mov.

**Comment by kasakun** [comment]
Hi
The project is mainly based on openpose. I didn't attatch the origin file because you can find it on https://github.com/CMU-Perceptual-Computing-Lab/openpose

The core of the software is that it reads the json output from openpose and calculate the velocity of the body.  The flaw of this project is that I didnt embed openpose into my project due to DDL. If you have much time, you can try embeding the code in your work.

Good Luck

**Comment by shootingliu** [comment]
Hi @kasakun 

- Do you mean dll?

- I have already use the openpose, should I do something else to contact it with your job?  Will it work when I test with your test video which already has the keypoint.json？

- And I also want to do a similar job which contains some other detection like fighting. So I am reading the code to find some suggestion.

- That will be really thankful if you could send me your test video.<350417319@qq.com>

Thanks a lot.

**Comment by kasakun** [comment]
1. No

2. If you check the `Detection` repo, you can find a folder called `sub_bg15`. It is a sample extracted from 
the video by openpose. You can use command line to extract the same data. The sub_bg contains two folders. One contains images which are only for visualization. The other contains the keypoints-time data that the software use. 

3. Fighting is sort of complex motion. I am not sure simply taking positions of hands and feet into consideration will work. You can test or check paper for it.

4. Later I will send you a email with the download link. Maybe you need VPN to access dropbox in mainland China. If you fail to access, please let me know.

Best
Zeyu

**Comment by shootingliu** [comment]
Hi @kasakun
I am sorry to say I failed to download the test video with VPN , AND I have messaged to you in dropbox.

**Comment by xwr96** [comment]
@shootingliu 你好，能把测试视频发给我吗？我的邮箱是1341917538@qq.com
