### ISSUE TITLE
AttributeError: module 'skvideo.io' has no attribute 'VideoCapture'

### ISSUE THREAD

**Issue by visakh7843** [kasakun/Fall-Detection#2]
getting this error while running the preprocessing file (both scripts)

**Comment by kasakun** [comment]
Make sure you have installed skvideo module.
There is some problem with the lib I use. I am not sure the updated version is better.

**Comment by visakh7843** [comment]
i have installed skvideo.Still i am getting the error!!!

```
visakh@visakh-Inspiron-5521:~/Documents/Main Project/Fall-Detection1/Preprocessing$ python3 preproc_batch.py 
Traceback (most recent call last):
  File "preproc_batch.py", line 17, in <module>
    cap = sv.VideoCapture(data_path + fn)
AttributeError: module 'skvideo.io' has no attribute 'VideoCapture'
```
i have no problem importing skvideo
```

visakh@visakh-Inspiron-5521:~/Documents/Main Project/Fall-Detection1/Preprocessing$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import skvideo
```

**Comment by kasakun** [comment]
Hope you are doing well.
My vm is down so I cannot reconstruct the environment. 

What I remind is the module I install is scikit-video(It seems the old version of skvideo). I am not sure they have already fixed the bug and merge these two packages yet.

Try
```
 $ sudo pip install scikit-video
```

Hope it works for you. If not, I suggest using other library to open the video.
